Setup CI/CD to produce binaries on release/tag
AOx0/adam pull request #78
Opened 2024-11-27 22:21 UTC by enriquegomeztagle

Related to #71

Add steps to produce binaries on release/tag.

* **justfile**:
  - Add a new `build-release` command to build the project in release mode.

* **.github/workflows/ci.yml**:
  - Add a new job to produce binaries on release/tag.
  - Add steps to build the project and upload binaries as artifacts.

* **xtask/src/build.rs**:
  - Add steps to produce binaries on release/tag.

* **xtask/src/build_ebpf.rs**:
  - Add steps to produce binaries on release/tag.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/AOx0/adam/issues/71?shareId=XXXX-XXXX-XXXX-XXXX).

2024-11-27 22:30 UTC, AOx0 requested changes
The modification of xtask is not necessary and the `build` target in the `justfile` should be enough:

```
just build --release
```

2024-11-27 22:30 UTC, AOx0 commented on .github/workflows/ci.yml
> +      - run: just build-release
This should be enough, it is not necessary to create a new target in the `justfile`:

```sh
just build --release
```

2024-11-27 22:30 UTC, AOx0 commented on justfile
> +    RUST_LOG=info cargo build --release
Not necessary, the `build` target already handles release builds:

```
just build --release 
```

2024-11-27 22:30 UTC, AOx0 commented on xtask/src/build.rs
> +    pub produce_binaries: bool,
I believe this is not necessary

2024-11-27 22:30 UTC, AOx0 commented on xtask/src/build.rs
> +
I believe this is not necessary

2024-11-27 23:02 UTC, enriquegomeztagle commented
@AOx0 can you check again, please?

2024-11-27 23:02 UTC, enriquegomeztagle commented
@AOx0 can you check again, please?

2024-11-28 00:23 UTC, AOx0 requested changes

2024-11-28 00:23 UTC, AOx0 commented on .github/workflows/ci.yml
> +            ./target/release/
I'm not sure if copying the entire release folder is the correct approach. Can we maybe just copy `firewall`, `controller`, `front`? Or are there any existing CI actions to publish binaries from a workspace?

2024-11-28 16:18 UTC, merged

2024-11-28 16:18 UTC, AOx0 commented
Thank youuu :D